name: Build & Publish Image
on:
  push:
    branches:
      - main
      - endpoint-change

jobs:
  build_and_publish_pg_dump_s3:
    name: Build and Publish pg_dump_s3
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/endpoint-change'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get short commit hash for image tag
        id: shortened_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
            POSTGRES_IMAGE_TAG=13
          tags: |
            ghcr.io/sit-digicre/pg_dump_s3:latest
            ghcr.io/sit-digicre/pg_dump_s3:${{ steps.shortened_hash.outputs.sha_short }}
